//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boods.en_US {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BoodsCommonLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoodsCommonLibrary() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Boods.en_US.BoodsCommonLibrary", typeof(BoodsCommonLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search the data in the XML version of the media failed to parameters ({0}, {1}, {2}) {3}.
        /// </summary>
        internal static string Asset_GetInfoFromMetadata_Exception {
            get {
                return ResourceManager.GetString("Asset_GetInfoFromMetadata_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infinite loop detected!.
        /// </summary>
        internal static string Asset_ToXmlForMedia_Exception {
            get {
                return ResourceManager.GetString("Asset_ToXmlForMedia_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The asset of SpecificId {0} child of the asset id {1} does not exist in the database..
        /// </summary>
        internal static string ASSETS_AddAsset_Child_NotExist {
            get {
                return ResourceManager.GetString("ASSETS_AddAsset_Child_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The asset of SpecificId {0} parent asset id {1} does not exist in the database..
        /// </summary>
        internal static string ASSETS_AddAsset_Parent_NotExist {
            get {
                return ResourceManager.GetString("ASSETS_AddAsset_Parent_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add to Cart.
        /// </summary>
        internal static string ASSETS_AddAssetsToBasket {
            get {
                return ResourceManager.GetString("ASSETS_AddAssetsToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Medias are successfully added to cart..
        /// </summary>
        internal static string ASSETS_AddAssetsToBasket_Success {
            get {
                return ResourceManager.GetString("ASSETS_AddAssetsToBasket_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adding a assetType.
        /// </summary>
        internal static string ASSETS_AddAssetTypeByName {
            get {
                return ResourceManager.GetString("ASSETS_AddAssetTypeByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verification of the existence of the asset {0}.
        /// </summary>
        internal static string ASSETS_CheckAssetField {
            get {
                return ResourceManager.GetString("ASSETS_CheckAssetField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting an asset.
        /// </summary>
        internal static string ASSETS_DeleteAsset {
            get {
                return ResourceManager.GetString("ASSETS_DeleteAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encountered Error while deleting an asset.
        /// </summary>
        internal static string ASSETS_DeleteAsset_Error {
            get {
                return ResourceManager.GetString("ASSETS_DeleteAsset_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error encountered while deleting an asset.
        /// </summary>
        internal static string ASSETS_DeleteAsset_Full {
            get {
                return ResourceManager.GetString("ASSETS_DeleteAsset_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting asset {0}.
        /// </summary>
        internal static string ASSETS_DeleteAsset_Short {
            get {
                return ResourceManager.GetString("ASSETS_DeleteAsset_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The asset {0} has-been removed successfully.
        /// </summary>
        internal static string ASSETS_DeleteAsset_Success {
            get {
                return ResourceManager.GetString("ASSETS_DeleteAsset_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The asset id {0} [SpecificId: {1}] type {2} could not be inserted because the constraint &lt;b&gt; acyclicity_constraint &lt;/ b&gt; prohibits the current asset have children and that One of these children is a parent..
        /// </summary>
        internal static string ASSETS_Exception {
            get {
                return ResourceManager.GetString("ASSETS_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error was encountered while adding an asset.
        /// </summary>
        internal static string ASSETS_Exception_Full {
            get {
                return ResourceManager.GetString("ASSETS_Exception_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adding an asset.
        /// </summary>
        internal static string ASSETS_Exception_Short {
            get {
                return ResourceManager.GetString("ASSETS_Exception_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving children asset {0}.
        /// </summary>
        internal static string ASSETS_GetAllAssetChildren {
            get {
                return ResourceManager.GetString("ASSETS_GetAllAssetChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ASSETS_GetAllAssetChildrenIds {0}.
        /// </summary>
        internal static string ASSETS_GetAllAssetChildrenIds {
            get {
                return ResourceManager.GetString("ASSETS_GetAllAssetChildrenIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving relatives of asset {0}.
        /// </summary>
        internal static string ASSETS_GetAllAssetParents {
            get {
                return ResourceManager.GetString("ASSETS_GetAllAssetParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recovery of assets.
        /// </summary>
        internal static string ASSETS_GetAllAssets {
            get {
                return ResourceManager.GetString("ASSETS_GetAllAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving Children Level 1.
        /// </summary>
        internal static string ASSETS_GetAssetChildrenLevelOne {
            get {
                return ResourceManager.GetString("ASSETS_GetAssetChildrenLevelOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving relatives of asset {0}.
        /// </summary>
        internal static string ASSETS_GetAssetParentsLevelOne {
            get {
                return ResourceManager.GetString("ASSETS_GetAssetParentsLevelOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à State recovery of the asset.
        /// </summary>
        internal static string ASSETS_GetAssetPublicationStatus {
            get {
                return ResourceManager.GetString("ASSETS_GetAssetPublicationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving BroadCastInfos of asset Id {0}.
        /// </summary>
        internal static string ASSETS_GetBroadcastInfo {
            get {
                return ResourceManager.GetString("ASSETS_GetBroadcastInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Media release dates..
        /// </summary>
        internal static string ASSETS_GetBroadcastInfo_Comment {
            get {
                return ResourceManager.GetString("ASSETS_GetBroadcastInfo_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Release dates of other media in the same program..
        /// </summary>
        internal static string ASSETS_GetBroadcastInfo_Comment_First {
            get {
                return ResourceManager.GetString("ASSETS_GetBroadcastInfo_Comment_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recovery of assets direct children of the asset {0}.
        /// </summary>
        internal static string ASSETS_GetChildrenLevelOneSpecificIds {
            get {
                return ResourceManager.GetString("ASSETS_GetChildrenLevelOneSpecificIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving metadata fields.
        /// </summary>
        internal static string ASSETS_GetFieldsListByAssetId {
            get {
                return ResourceManager.GetString("ASSETS_GetFieldsListByAssetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error retrieving the url of the specific asset id {0}, {1} title.
        /// </summary>
        internal static string ASSETS_GetFileUrlByModsWebserice_Full {
            get {
                return ResourceManager.GetString("ASSETS_GetFileUrlByModsWebserice_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving URL from Mods.
        /// </summary>
        internal static string ASSETS_GetFileUrlByModsWebserice_Short {
            get {
                return ResourceManager.GetString("ASSETS_GetFileUrlByModsWebserice_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error was encountered while retrieving the video associated with asset.
        /// </summary>
        internal static string ASSETS_GetMediaDetails_Full {
            get {
                return ResourceManager.GetString("ASSETS_GetMediaDetails_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recovery associated with the video asset.
        /// </summary>
        internal static string ASSETS_GetMediaDetails_Short {
            get {
                return ResourceManager.GetString("ASSETS_GetMediaDetails_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving the type of relationship: {0}.
        /// </summary>
        internal static string ASSETS_GetTypeRelationByName {
            get {
                return ResourceManager.GetString("ASSETS_GetTypeRelationByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verification of the existence of the asset {0}.
        /// </summary>
        internal static string ASSETS_IsAssetPublished {
            get {
                return ResourceManager.GetString("ASSETS_IsAssetPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to delete the relationships.
        /// </summary>
        internal static string ASSETS_Relation {
            get {
                return ResourceManager.GetString("ASSETS_Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Removing the basket.
        /// </summary>
        internal static string ASSETS_RemoveAssetsFromBasket {
            get {
                return ResourceManager.GetString("ASSETS_RemoveAssetsFromBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Media removed from the cart successfully..
        /// </summary>
        internal static string ASSETS_RemoveAssetsFromBasket_Success {
            get {
                return ResourceManager.GetString("ASSETS_RemoveAssetsFromBasket_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The asset id {0} [SpecificId: {1}] type {2} could not be inserted because the constraint &lt;b&gt; acyclicity_constraint &lt;/ b&gt; prohibits the current asset have children and that One of these children is a parent..
        /// </summary>
        internal static string ASSETS_UpdateAsset_Exception {
            get {
                return ResourceManager.GetString("ASSETS_UpdateAsset_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error was encountered while updating an asset.
        /// </summary>
        internal static string ASSETS_UpdateAsset_Exception_Full {
            get {
                return ResourceManager.GetString("ASSETS_UpdateAsset_Exception_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updating an asset.
        /// </summary>
        internal static string ASSETS_UpdateAsset_Exception_Short {
            get {
                return ResourceManager.GetString("ASSETS_UpdateAsset_Exception_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The picture {0} could not be served &lt;br /&gt;.
        /// </summary>
        internal static string ASSETS_UpdateAsset_Image_CannotDelete {
            get {
                return ResourceManager.GetString("ASSETS_UpdateAsset_Image_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purge image {0} completed successfully &lt;br /&gt;.
        /// </summary>
        internal static string ASSETS_UpdateAsset_Image_Delete {
            get {
                return ResourceManager.GetString("ASSETS_UpdateAsset_Image_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file {0} image {1} does not exist.
        /// </summary>
        internal static string ASSETS_UpdateAsset_Image_NotExist {
            get {
                return ResourceManager.GetString("ASSETS_UpdateAsset_Image_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The asset you want to update does not exist in the database.
        /// </summary>
        internal static string ASSETS_UpdateAsset_NotFound {
            get {
                return ResourceManager.GetString("ASSETS_UpdateAsset_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection between the video asset {0} and {1} picture asset deleted. &lt;br /&gt;.
        /// </summary>
        internal static string ASSETS_UpdateAsset_Video_Image_Delete {
            get {
                return ResourceManager.GetString("ASSETS_UpdateAsset_Video_Image_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: Unable to access the data logger {0}.
        /// </summary>
        internal static string BoodsLogger_Attribute_Message {
            get {
                return ResourceManager.GetString("BoodsLogger_Attribute_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message from the InnerException: {0}.
        /// </summary>
        internal static string BoodsLogger_GetDisplayInnserMessage {
            get {
                return ResourceManager.GetString("BoodsLogger_GetDisplayInnserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message: {0}.
        /// </summary>
        internal static string BoodsLogger_GetDisplayMessage {
            get {
                return ResourceManager.GetString("BoodsLogger_GetDisplayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error was encountered while compressing images: {0}.
        /// </summary>
        internal static string CompressAndSaveProcess_ProcessImage {
            get {
                return ResourceManager.GetString("CompressAndSaveProcess_ProcessImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The image could not be generated. {0} The byte size is too small to generate the image..
        /// </summary>
        internal static string CompressAndSaveProcess_SaveWithQualityFactor {
            get {
                return ResourceManager.GetString("CompressAndSaveProcess_SaveWithQualityFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving conductors.
        /// </summary>
        internal static string CONDUCTORS {
            get {
                return ResourceManager.GetString("CONDUCTORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving channels.
        /// </summary>
        internal static string CONDUCTORS_Channel {
            get {
                return ResourceManager.GetString("CONDUCTORS_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server=.\SQLExpress;Integrated security=SSPI;database=master.
        /// </summary>
        internal static string ConnectSQL {
            get {
                return ResourceManager.GetString("ConnectSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The context passed as a parameter can not be considered as a context data BOODSEntities.
        /// </summary>
        internal static string Context_NotValid {
            get {
                return ResourceManager.GetString("Context_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error was encountered while fl attempted cropping: {0}.
        /// </summary>
        internal static string CroppingProcess_ProcessImage {
            get {
                return ResourceManager.GetString("CroppingProcess_ProcessImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: Unable to enter the bose data logger.
        /// </summary>
        internal static string ErreurBaseDonneesLog {
            get {
                return ResourceManager.GetString("ErreurBaseDonneesLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à optionValues ​​must be filled because the type of validator is OPTIONLIST..
        /// </summary>
        internal static string Field_Valid_Exception {
            get {
                return ResourceManager.GetString("Field_Valid_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adding a Field.
        /// </summary>
        internal static string FIELDS {
            get {
                return ResourceManager.GetString("FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creating the filter.
        /// </summary>
        internal static string FILTERS_CreateFilter {
            get {
                return ResourceManager.GetString("FILTERS_CreateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove filter.
        /// </summary>
        internal static string FILTERS_DeleteFilter {
            get {
                return ResourceManager.GetString("FILTERS_DeleteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recovery filters user {0}.
        /// </summary>
        internal static string FILTERS_GetFiltersByUserName {
            get {
                return ResourceManager.GetString("FILTERS_GetFiltersByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvergarde filter.
        /// </summary>
        internal static string FILTERS_UpdateFilter {
            get {
                return ResourceManager.GetString("FILTERS_UpdateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred innaltendue.
        /// </summary>
        internal static string FORMATS_GetAllFormats_Full {
            get {
                return ResourceManager.GetString("FORMATS_GetAllFormats_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving formats.
        /// </summary>
        internal static string FORMATS_GetAllFormats_Short {
            get {
                return ResourceManager.GetString("FORMATS_GetAllFormats_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving formats scaled images.
        /// </summary>
        internal static string FORMATS_GetTransformedImageFormats {
            get {
                return ResourceManager.GetString("FORMATS_GetTransformedImageFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred innaltendue.
        /// </summary>
        internal static string FORMATS_InsertFormat_Full {
            get {
                return ResourceManager.GetString("FORMATS_InsertFormat_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert size.
        /// </summary>
        internal static string FORMATS_InsertFormat_Short {
            get {
                return ResourceManager.GetString("FORMATS_InsertFormat_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The processing of the file failed. Error: {0}.
        /// </summary>
        internal static string ImageProcessingUtilities_CreateImage_Error {
            get {
                return ResourceManager.GetString("ImageProcessingUtilities_CreateImage_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No format has been specified.
        /// </summary>
        internal static string ImageProcessingUtilities_CreateImage_outputMessage {
            get {
                return ResourceManager.GetString("ImageProcessingUtilities_CreateImage_outputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The extension associated with the format file {0} is not given.
        /// </summary>
        internal static string ImageProcessingUtilities_CreateImage_outputMessage_Add {
            get {
                return ResourceManager.GetString("ImageProcessingUtilities_CreateImage_outputMessage_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The processing of the image could not be performed because the loading logo {0} [URL = {1}] failed: {2}.
        /// </summary>
        internal static string ImageProcessingUtilities_CreateImage_outputMessage_Logo {
            get {
                return ResourceManager.GetString("ImageProcessingUtilities_CreateImage_outputMessage_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The processing of the image could not be performed because the loading maie-louise {0} [URL = {1}] failed: {2}.
        /// </summary>
        internal static string ImageProcessingUtilities_CreateImage_outputMessage_ML {
            get {
                return ResourceManager.GetString("ImageProcessingUtilities_CreateImage_outputMessage_ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The url of the file is empty..
        /// </summary>
        internal static string ImageProcessingUtilities_CreateImage_Url_Empty {
            get {
                return ResourceManager.GetString("ImageProcessingUtilities_CreateImage_Url_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infinite loop detected!.
        /// </summary>
        internal static string Infinite_Loop_Exception {
            get {
                return ResourceManager.GetString("Infinite_Loop_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not find {0}.
        /// </summary>
        internal static string IniParser_File_NotFound_Exception {
            get {
                return ResourceManager.GetString("IniParser_File_NotFound_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stopping the application (time = {0})..
        /// </summary>
        internal static string LocalTools_ApplicationEnd {
            get {
                return ResourceManager.GetString("LocalTools_ApplicationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start the application..
        /// </summary>
        internal static string LocalTools_ApplicationStart {
            get {
                return ResourceManager.GetString("LocalTools_ApplicationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation Association {0} &lt;br/&gt; [Group publication = {4}] {5} &lt;br/&gt; &lt;br/&gt; {6} &lt;br/&gt; [Publication {2} = {7}] &lt;br / &gt; [Step {3} = {8}].
        /// </summary>
        internal static string LocalTools_CreateAssociation {
            get {
                return ResourceManager.GetString("LocalTools_CreateAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatic publication of media \ &quot;{0} \&quot; ({1}) on the heading \ &quot;{2} \&quot; ({3}) &lt;br/&gt; Group publication {4}, {5} step of publication.: {6}..
        /// </summary>
        internal static string LocalTools_CreateAutomaticPublication {
            get {
                return ResourceManager.GetString("LocalTools_CreateAutomaticPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creating group publications [Group Id = {0}; User = {1}] = {2} User.
        /// </summary>
        internal static string LocalTools_CreateGroupPublication {
            get {
                return ResourceManager.GetString("LocalTools_CreateGroupPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation of the platform [{0}: {1}]..
        /// </summary>
        internal static string LocalTools_CreatePlatform {
            get {
                return ResourceManager.GetString("LocalTools_CreatePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profile creation \ &quot;{0} \&quot; (id = {1}, topics = [{2}])..
        /// </summary>
        internal static string LocalTools_CreateProfil {
            get {
                return ResourceManager.GetString("LocalTools_CreateProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publication of media \ &quot;{0} \&quot; ({1}) on the topic \ &quot;{2} \&quot; ({3}) &lt;br/&gt; Group publication {4}, {5} step of publication. {6}..
        /// </summary>
        internal static string LocalTools_CreatePublication {
            get {
                return ResourceManager.GetString("LocalTools_CreatePublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creating steps publication [Group Id = {0}, Id = {1} steps, User = {2}].
        /// </summary>
        internal static string LocalTools_CreatePublicationStep {
            get {
                return ResourceManager.GetString("LocalTools_CreatePublicationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation of the section [{0}: {1}]..
        /// </summary>
        internal static string LocalTools_CreateRubric {
            get {
                return ResourceManager.GetString("LocalTools_CreateRubric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation of user [{0}]..
        /// </summary>
        internal static string LocalTools_CreateUser {
            get {
                return ResourceManager.GetString("LocalTools_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression Association &lt;br/&gt; [Group publication = {0}] &lt;br/&gt; [Item = {1}] &lt;br/&gt; [Media = {2}].
        /// </summary>
        internal static string LocalTools_DeleteAssociation {
            get {
                return ResourceManager.GetString("LocalTools_DeleteAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forced removal of the platform [{0}] &lt;br/&gt; deleted [{1}] subheadings..
        /// </summary>
        internal static string LocalTools_DeleteForcePlatform {
            get {
                return ResourceManager.GetString("LocalTools_DeleteForcePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove the section [{0}] &lt;br/&gt; subheadings deleted [{1}]..
        /// </summary>
        internal static string LocalTools_DeleteForceRubric {
            get {
                return ResourceManager.GetString("LocalTools_DeleteForceRubric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting Group publication [Group Id = {0}; User = {1}].
        /// </summary>
        internal static string LocalTools_DeleteGroupPublication {
            get {
                return ResourceManager.GetString("LocalTools_DeleteGroupPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove the platform [{0}]..
        /// </summary>
        internal static string LocalTools_DeletePlatform {
            get {
                return ResourceManager.GetString("LocalTools_DeletePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting profile \ &quot;{0} \&quot; (id = {1})..
        /// </summary>
        internal static string LocalTools_DeleteProfil {
            get {
                return ResourceManager.GetString("LocalTools_DeleteProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove the media publication {0} on {1} section. &lt;br/&gt; Group publication {2}, {3} Id publication..
        /// </summary>
        internal static string LocalTools_DeletePublication {
            get {
                return ResourceManager.GetString("LocalTools_DeletePublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Removal steps of publication [Group Id = {0}, Id = {1} steps, User = {2}].
        /// </summary>
        internal static string LocalTools_DeletePublicationStep {
            get {
                return ResourceManager.GetString("LocalTools_DeletePublicationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove the section [{0}]..
        /// </summary>
        internal static string LocalTools_DeleteRubric {
            get {
                return ResourceManager.GetString("LocalTools_DeleteRubric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete user [{0}]..
        /// </summary>
        internal static string LocalTools_DeleteUser {
            get {
                return ResourceManager.GetString("LocalTools_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed Identification (User = {0})..
        /// </summary>
        internal static string LocalTools_LoginFailure {
            get {
                return ResourceManager.GetString("LocalTools_LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changing the platform [{0}: {1}]..
        /// </summary>
        internal static string LocalTools_ModifyPlatform {
            get {
                return ResourceManager.GetString("LocalTools_ModifyPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changing the profile \ &quot;{0} \&quot; (id = {1}, topics = [{2}])..
        /// </summary>
        internal static string LocalTools_ModifyProfil {
            get {
                return ResourceManager.GetString("LocalTools_ModifyProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publication of media \ &quot;{0} \&quot; ({1}) on the topic \ &quot;{2} \&quot; ({3}) &lt;br/&gt; Group publication {4}, {5} step of publication. { 6}..
        /// </summary>
        internal static string LocalTools_ModifyPublication {
            get {
                return ResourceManager.GetString("LocalTools_ModifyPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changing the profile \ &quot;{0} \&quot;, renamed \ &quot;{1} \&quot; (id = {2}, topics = [{3}])..
        /// </summary>
        internal static string LocalTools_ModifyRenameProfil {
            get {
                return ResourceManager.GetString("LocalTools_ModifyRenameProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changing the section [{0}: {1}]..
        /// </summary>
        internal static string LocalTools_ModifyRubric {
            get {
                return ResourceManager.GetString("LocalTools_ModifyRubric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End of session (id = {0}, length = {1})..
        /// </summary>
        internal static string LocalTools_SessionEnd {
            get {
                return ResourceManager.GetString("LocalTools_SessionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Beginning of the session (id = {0})..
        /// </summary>
        internal static string LocalTools_SessionStart {
            get {
                return ResourceManager.GetString("LocalTools_SessionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update user [{0}]..
        /// </summary>
        internal static string LocalTools_UpdateUser {
            get {
                return ResourceManager.GetString("LocalTools_UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login User {0} (sessionID = {1})..
        /// </summary>
        internal static string LocalTools_UserConnect {
            get {
                return ResourceManager.GetString("LocalTools_UserConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnecting the user {0} (sessionID = {1})..
        /// </summary>
        internal static string LocalTools_UserLogout {
            get {
                return ResourceManager.GetString("LocalTools_UserLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log error: {0}.
        /// </summary>
        internal static string LoggerException {
            get {
                return ResourceManager.GetString("LoggerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à impossible to open or write to the file: {0}.
        /// </summary>
        internal static string MessageErreurAccesFichier {
            get {
                return ResourceManager.GetString("MessageErreurAccesFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timeout: Can not access the mutex after {0} milliseconds.
        /// </summary>
        internal static string MessageTimeout {
            get {
                return ResourceManager.GetString("MessageTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error was encountered while creating the publication.
        /// </summary>
        internal static string ORGA_CreatePublications_Full {
            get {
                return ResourceManager.GetString("ORGA_CreatePublications_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rules in associaition:.
        /// </summary>
        internal static string ORGA_CreatePublications_Rule {
            get {
                return ResourceManager.GetString("ORGA_CreatePublications_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creating publications.
        /// </summary>
        internal static string ORGA_CreatePublications_Short {
            get {
                return ResourceManager.GetString("ORGA_CreatePublications_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This entity is already associated with diffusion media can not be deleted.
        /// </summary>
        internal static string ORGA_DeleteDiffusionEntite_Association_Error {
            get {
                return ResourceManager.GetString("ORGA_DeleteDiffusionEntite_Association_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An entity child had to be created from the opening broadcast of the screen, in this case the removal is impossible..
        /// </summary>
        internal static string ORGA_DeleteDiffusionEntite_Relation_Error {
            get {
                return ResourceManager.GetString("ORGA_DeleteDiffusionEntite_Relation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to delete a nonexistent publication.
        /// </summary>
        internal static string ORGA_DeletePublication {
            get {
                return ResourceManager.GetString("ORGA_DeletePublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error was encountered while deleting the publication of id {0}.
        /// </summary>
        internal static string ORGA_DeletePublication_Full {
            get {
                return ResourceManager.GetString("ORGA_DeletePublication_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting a publication.
        /// </summary>
        internal static string ORGA_DeletePublication_Short {
            get {
                return ResourceManager.GetString("ORGA_DeletePublication_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Broadcasting entity not found..
        /// </summary>
        internal static string ORGA_EntityDiffusion_NotFound {
            get {
                return ResourceManager.GetString("ORGA_EntityDiffusion_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insufficient permission to display this item..
        /// </summary>
        internal static string ORGA_GetEntiteDiffusion {
            get {
                return ResourceManager.GetString("ORGA_GetEntiteDiffusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data recovery fast simulation.
        /// </summary>
        internal static string ORGA_GetFastSimulationXML_Exception {
            get {
                return ResourceManager.GetString("ORGA_GetFastSimulationXML_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The platform Id {0} does not exist..
        /// </summary>
        internal static string ORGA_GetFastSimulationXML_Platform_NotExist {
            get {
                return ResourceManager.GetString("ORGA_GetFastSimulationXML_Platform_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This entity is not a platform because it has a parent section..
        /// </summary>
        internal static string ORGA_GetPlateformeById {
            get {
                return ResourceManager.GetString("ORGA_GetPlateformeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreure is a surevenue.
        /// </summary>
        internal static string ORGA_GetPlateformeById_Full {
            get {
                return ResourceManager.GetString("ORGA_GetPlateformeById_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recovery palteforme {0}.
        /// </summary>
        internal static string ORGA_GetPlateformeById_Short {
            get {
                return ResourceManager.GetString("ORGA_GetPlateformeById_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreure is a surevenue.
        /// </summary>
        internal static string ORGA_GetPlateformeOfRubrique_Full {
            get {
                return ResourceManager.GetString("ORGA_GetPlateformeOfRubrique_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recovery palteforme heading {0}.
        /// </summary>
        internal static string ORGA_GetPlateformeOfRubrique_Short {
            get {
                return ResourceManager.GetString("ORGA_GetPlateformeOfRubrique_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error was encountered while rcupération information purge.
        /// </summary>
        internal static string ORGA_GetRubriquePurgeInfos_Full {
            get {
                return ResourceManager.GetString("ORGA_GetRubriquePurgeInfos_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error retrieving information purge.
        /// </summary>
        internal static string ORGA_GetRubriquePurgeInfos_Short {
            get {
                return ResourceManager.GetString("ORGA_GetRubriquePurgeInfos_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving SentVersionProperties.
        /// </summary>
        internal static string ORGA_GetSentVersionPropertiesByPlateformeId {
            get {
                return ResourceManager.GetString("ORGA_GetSentVersionPropertiesByPlateformeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recovery under headings {0}.
        /// </summary>
        internal static string ORGA_GetSousRubriques {
            get {
                return ResourceManager.GetString("ORGA_GetSousRubriques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialization publication.
        /// </summary>
        internal static string ORGA_InitializePublicationStatus {
            get {
                return ResourceManager.GetString("ORGA_InitializePublicationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not modify nonexistent publication.
        /// </summary>
        internal static string ORGA_ModifyPublication {
            get {
                return ResourceManager.GetString("ORGA_ModifyPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error was encountered while changing the publication id {0}.
        /// </summary>
        internal static string ORGA_ModifyPublication_Full {
            get {
                return ResourceManager.GetString("ORGA_ModifyPublication_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editing a publication.
        /// </summary>
        internal static string ORGA_ModifyPublication_Short {
            get {
                return ResourceManager.GetString("ORGA_ModifyPublication_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [No Right].
        /// </summary>
        internal static string ORGA_NoRight {
            get {
                return ResourceManager.GetString("ORGA_NoRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à platform.
        /// </summary>
        internal static string ORGA_Platform {
            get {
                return ResourceManager.GetString("ORGA_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - The {0} has attriuts &lt;br /&gt;..
        /// </summary>
        internal static string ORGA_PourquoiCetteEntiteNePourraitPasEtreSupprimee_HasAttributes {
            get {
                return ResourceManager.GetString("ORGA_PourquoiCetteEntiteNePourraitPasEtreSupprimee_HasAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - The media have been sent and are still present in the {0} &lt;br /&gt;..
        /// </summary>
        internal static string ORGA_PourquoiCetteEntiteNePourraitPasEtreSupprimee_HasMedias {
            get {
                return ResourceManager.GetString("ORGA_PourquoiCetteEntiteNePourraitPasEtreSupprimee_HasMedias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - Publications have been made ​​in this {0} &lt;br /&gt;..
        /// </summary>
        internal static string ORGA_PourquoiCetteEntiteNePourraitPasEtreSupprimee_HasPublications {
            get {
                return ResourceManager.GetString("ORGA_PourquoiCetteEntiteNePourraitPasEtreSupprimee_HasPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - This {0} contains one or more sub-categories &lt;br /&gt;..
        /// </summary>
        internal static string ORGA_PourquoiCetteEntiteNePourraitPasEtreSupprimee_HasRubrics {
            get {
                return ResourceManager.GetString("ORGA_PourquoiCetteEntiteNePourraitPasEtreSupprimee_HasRubrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - Automatic rules use this {0} &lt;br /&gt;..
        /// </summary>
        internal static string ORGA_PourquoiCetteEntiteNePourraitPasEtreSupprimee_HasRules {
            get {
                return ResourceManager.GetString("ORGA_PourquoiCetteEntiteNePourraitPasEtreSupprimee_HasRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à rubric.
        /// </summary>
        internal static string ORGA_Rubric {
            get {
                return ResourceManager.GetString("ORGA_Rubric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User not found.
        /// </summary>
        internal static string ORGA_User_NotFound {
            get {
                return ResourceManager.GetString("ORGA_User_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error was encountered during the process of combining with another image: {0}.
        /// </summary>
        internal static string PasteImageProcess_ProcessImage {
            get {
                return ResourceManager.GetString("PasteImageProcess_ProcessImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unsupported type.
        /// </summary>
        internal static string Period_Type_Exception {
            get {
                return ResourceManager.GetString("Period_Type_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boods Export Context - Platform {0} (ID {1}).
        /// </summary>
        internal static string Platform_GetInfo {
            get {
                return ResourceManager.GetString("Platform_GetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The component type of filter is not a DropDownList.
        /// </summary>
        internal static string Predicate_DropDownListValues_Exception {
            get {
                return ResourceManager.GetString("Predicate_DropDownListValues_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à an exception was encountered during redimenssionnement image: {0}.
        /// </summary>
        internal static string ResizeProcess_ProcessImage {
            get {
                return ResourceManager.GetString("ResizeProcess_ProcessImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The rule you want to apply does not exist..
        /// </summary>
        internal static string RULES_ApplyRule {
            get {
                return ResourceManager.GetString("RULES_ApplyRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application of automatic rule: {0}. The media {1} with the title: {2} was not associated with the rule {3} as no release date has been found valid. &lt;br /&gt;.
        /// </summary>
        internal static string RULES_AppplicateAutomaticRules {
            get {
                return ResourceManager.GetString("RULES_AppplicateAutomaticRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The start date and an end date were retrieved from the xml file then input the rules to use must be one step publication..
        /// </summary>
        internal static string RULES_CreateEtapesPublication {
            get {
                return ResourceManager.GetString("RULES_CreateEtapesPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rule creation.
        /// </summary>
        internal static string RULES_CreateRule {
            get {
                return ResourceManager.GetString("RULES_CreateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error was encountered while deleting a rule..
        /// </summary>
        internal static string RULES_DeleteRule_Full {
            get {
                return ResourceManager.GetString("RULES_DeleteRule_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting a Rule.
        /// </summary>
        internal static string RULES_DeleteRule_Short {
            get {
                return ResourceManager.GetString("RULES_DeleteRule_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving rules of images of category filter: {0}.
        /// </summary>
        internal static string RULES_GetImageRulesByRubriqueFiltrage {
            get {
                return ResourceManager.GetString("RULES_GetImageRulesByRubriqueFiltrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving rules of images of category filter: {0}.
        /// </summary>
        internal static string RULES_GetImageRulesIdByRubriqueFiltrage {
            get {
                return ResourceManager.GetString("RULES_GetImageRulesIdByRubriqueFiltrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error was encountered during the implementation of the rule {0}..
        /// </summary>
        internal static string RULES_UpdateRule_Full {
            get {
                return ResourceManager.GetString("RULES_UpdateRule_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update rule.
        /// </summary>
        internal static string RULES_UpdateRule_Short {
            get {
                return ResourceManager.GetString("RULES_UpdateRule_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatic association.
        /// </summary>
        internal static string SCHD_CreateAssociations {
            get {
                return ResourceManager.GetString("SCHD_CreateAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import rule: {0}.
        /// </summary>
        internal static string SCHD_CreateAssociations_Rule {
            get {
                return ResourceManager.GetString("SCHD_CreateAssociations_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disk Space.
        /// </summary>
        internal static string SCHD_GetFreeDiskSpace_Disk_Space {
            get {
                return ResourceManager.GetString("SCHD_GetFreeDiskSpace_Disk_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login or password incorrect..
        /// </summary>
        internal static string SCHD_GetFreeDiskSpace_Login_Password_NotCorrect {
            get {
                return ResourceManager.GetString("SCHD_GetFreeDiskSpace_Login_Password_NotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login or incorrect password to connect to the remote machine ...
        /// </summary>
        internal static string SCHD_GetFreeDiskSpace_Login_Password_NotCorrect_Full {
            get {
                return ResourceManager.GetString("SCHD_GetFreeDiskSpace_Login_Password_NotCorrect_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to connect to the machine..
        /// </summary>
        internal static string SCHD_GetFreeDiskSpace_Machin_NotConnected {
            get {
                return ResourceManager.GetString("SCHD_GetFreeDiskSpace_Machin_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retrieving publications platform {0}.
        /// </summary>
        internal static string SCHD_GetPublicationsByLoadingTypeAndPlateformeId {
            get {
                return ResourceManager.GetString("SCHD_GetPublicationsByLoadingTypeAndPlateformeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error when resetting the asset id {0}.
        /// </summary>
        internal static string SCHD_ReinitializePublicationStatus {
            get {
                return ResourceManager.GetString("SCHD_ReinitializePublicationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error saving the asset {0} of type {1}: {2}..
        /// </summary>
        internal static string SqlAssetManager_SaveAsset_Exception {
            get {
                return ResourceManager.GetString("SqlAssetManager_SaveAsset_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When you import the file, several nodes publications were found when he should find one. The application of automatic rules is not performed..
        /// </summary>
        internal static string SqlAssetManager_SaveAsset_Publication_Exception {
            get {
                return ResourceManager.GetString("SqlAssetManager_SaveAsset_Publication_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creating a publication made ​​successfully under {0} with the start date {1} and the end date {2} &lt;br /&gt;.
        /// </summary>
        internal static string SqlAssetManager_SaveAsset_Success {
            get {
                return ResourceManager.GetString("SqlAssetManager_SaveAsset_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To save folder does not exist in the database..
        /// </summary>
        internal static string SqlFilterStorer_Context_NotExist {
            get {
                return ResourceManager.GetString("SqlFilterStorer_Context_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rule {0} does not exist..
        /// </summary>
        internal static string SqlRuleStorer_NotValid {
            get {
                return ResourceManager.GetString("SqlRuleStorer_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type provided must be an Enum. Type {0}.
        /// </summary>
        internal static string StringEnum_Exception {
            get {
                return ResourceManager.GetString("StringEnum_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ~ ~ Not Initialized.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Sending message to {0} failed.
        /// </summary>
        internal static string Tools_SendMail_Exception {
            get {
                return ResourceManager.GetString("Tools_SendMail_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Sending of message failed.
        /// </summary>
        internal static string Tools_SendMail_Warning_Full {
            get {
                return ResourceManager.GetString("Tools_SendMail_Warning_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Re-sending in 5 seconds.
        /// </summary>
        internal static string Tools_SendMail_Warning_Short {
            get {
                return ResourceManager.GetString("Tools_SendMail_Warning_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} day.
        /// </summary>
        internal static string Tools_TimeSpan_Format_Day {
            get {
                return ResourceManager.GetString("Tools_TimeSpan_Format_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} days.
        /// </summary>
        internal static string Tools_TimeSpan_Format_Days {
            get {
                return ResourceManager.GetString("Tools_TimeSpan_Format_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} hours.
        /// </summary>
        internal static string Tools_TimeSpan_Format_Hour {
            get {
                return ResourceManager.GetString("Tools_TimeSpan_Format_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} hours.
        /// </summary>
        internal static string Tools_TimeSpan_Format_Hours {
            get {
                return ResourceManager.GetString("Tools_TimeSpan_Format_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} minute.
        /// </summary>
        internal static string Tools_TimeSpan_Format_Minute {
            get {
                return ResourceManager.GetString("Tools_TimeSpan_Format_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} minutes.
        /// </summary>
        internal static string Tools_TimeSpan_Format_Minutes {
            get {
                return ResourceManager.GetString("Tools_TimeSpan_Format_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} second.
        /// </summary>
        internal static string Tools_TimeSpan_Format_Second {
            get {
                return ResourceManager.GetString("Tools_TimeSpan_Format_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} seconds.
        /// </summary>
        internal static string Tools_TimeSpan_Format_Seconds {
            get {
                return ResourceManager.GetString("Tools_TimeSpan_Format_Seconds", resourceCulture);
            }
        }
    }
}
